### PR TITLE
bump plugin to 0.9.0 and graphql to 0.6.0

### PR DESCRIPTION
**Pull request by akre54**

### CODE REVIEW

**Comment by schickling** [comment]
Awesome! Thanks! Could you please also make sure the example project is still working? 👍

**Comment by akre54** [comment]
Getting

```
ERROR in ./src/index.js
Module build failed: Error: Could not locate the bindings file. Tried:
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/build/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/build/Debug/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/build/Release/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/out/Debug/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/Debug/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/out/Release/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/Release/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/build/default/deasync.node
 → /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/compiled/6.0.0/darwin/x64/deasync.node
    at bindings (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/deasync/index.js:23:31)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-plugin-react-relay/lib/index.js:29:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 505 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 550 bytes {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 504 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.
```

**Comment by akre54** [comment]
Dunno if it was already broken (just tried blowing away node_modules and checking out master, then going from there)

Edit: Ok master works.

**Comment by akre54** [comment]
```
http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/adam/Projects/babel-plugin-react-relay/examples/schema
Hash: e2a1fab2f1d993dfabc2
Version: webpack 1.13.1
Time: 3446ms
     Asset       Size  Chunks             Chunk Names
index.html  126 bytes          [emitted]

ERROR in ./src/index.js
Module build failed: Error: Plugin 0 specified in "/Users/adam/Projects/babel-plugin-react-relay/examples/schema/.babelrc" provided an invalid property of "Environment"
    at Plugin.init (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/plugin.js:138:13)
    at Function.normalisePlugin (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:174:12)
    at /Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:208:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/adam/Projects/babel-plugin-react-relay/examples/schema/node_modules/babel-loader/index.js:88:12)
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 516 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 540 bytes {0} [built]
        [1] ./~/lodash/lodash.js 516 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.
```

**Comment by akre54** [comment]
I'm kind of stuck in dependency hell here. Any ideas?

**Comment by schickling** [comment]
Thanks for all your help @akre54. I could fix it myself. I've published a new version. Could you please confirm whether it works for you?

**Comment by akre54** [comment]
Fixed, thanks so much.

**Pull request closed without merging**
